<!DOCTYPE html>
<html lang="en">
<head>
  <title>Facilities</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
  .navbar-nav > li > a{
    padding: 25px;
  }
  .navbar-header{
    padding: 10px;
  }
  body
  {
    background-image: url(mainback.jpg);
    background-size: cover;
    background-position: center;
  }
  </style>
</head>
<body>
  
  <!--NAVIGATION BAR-->
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="temp3.php">Wellness Centre</a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="temp3.php">Home</a></li>
        <li class="active"><a href="Facilities.php">Facilities</a></li>
        <li><a href="Packages.php">Packages</a></li>
        <li><a href="Nutrition.php">Nutrition</a></li>
        <li><a href="About.php">About Us</a></li>
        <li><a href="Contact.php">Contact Us</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="Login.php"><span></span> Login</a></li>
      </ul>
    </div>
  </nav>
  <div class="container" style=" ">
  <h1><b><u>Facilities</u></b></h1>
  <br>
  
  
  <div class="container" style=" ">
  <img src="aerob.jpg" alt="Aerobics" style="width:300px; height:300px; margin-left:15px; float: left;
  border: 1px solid #ddd;
  border-radius: 25px;
  padding: 5px;
  margin-right:20px;
  margin-left:20px;
  margin-bottom:40px;">
  <h3><b>Aerobics</b></h3><br>
  <p style="font-size: 18px">
  
  Aerobics is a form of physical exercise that combines rhythmic aerobic exercise with stretching and 
strength training routines with the goal of 
improving all elements of fitness (flexibility, muscular strength, and cardio-vascular fitness). 
It is usually performed to music and may be practiced in a group setting led by an 
instructor (fitness professional), although it can be done solo and without musical accompaniment.
  
  <br><br>
  
  Aerobics helps in increasing the stamina and fat loss too in an efficient way. With our 
  trainers we are providing you the best exercises as per the body structure.
  </p>
  </div>

  
  <div class="container" style=" ">
  <img src="weight.jpeg" alt="Weight Training" style="width:300px; height:300px; margin-left:15px; float: right;
  border: 1px solid #ddd;
  border-radius: 25px;
  padding: 5px;
  margin-right:20px;
  margin-left:20px;
  margin-bottom:40px;">
  <h3><b>Weight Training</b></h3><br>
  <p style="font-size: 18px">

  Weight training is a common type of strength training for developing the strength and size of skeletal muscles.
It utilizes the force of gravity in the form of weighted bars, dumbbells or weight stacks in order to oppose 
the force generated by muscle through concentric or eccentric contraction. 
Weight training uses a variety of specialized equipment to target specific muscle groups and types of movement.

<br>
<br> 
 
  Building and maintaining muscle is necessary for all of us, especially 
  as we age. And the earlier we start, the better it 
  is. With our experienced trainers you can achieve it
  </p>
  </div>

  <div class="container" style=" ">
  <img src="yoga.jpeg" alt="Yoga" style="width:300px; height:300px; margin-left:15px; float: left;
  border: 1px solid #ddd;
  border-radius: 25px;
  padding: 5px;
  margin-right:20px;
  margin-left:20px;
  margin-bottom:40px;">
  <h3><b>Yoga</b></h3><br>
  <p style="font-size: 18px">
  Yoga is an ancient practice that may have originated in India. It involves movement, meditation, and 
  breathing techniques to promote mental and physical well-being.

  A regular yoga practice can promote endurance, strength, calmness, flexibility, and well-being.

  Yoga is now a popular form of exercise around the world. According to a 2017 national survey, 
  one in seven adults in the United States practiced yoga in the past 12 months.
<br>
<br>


  With us, you can find balance, harmony and energy in 
  the hectic hassle of everyday pressure and 
  deadlines. Relax and Enjoy the perfect experience of 
  a true Yoga at our studio. 
  </p>
  </div>  
  
  <div class="container" style=" ">
  <img src="counsel.jpeg" alt="Counselling" style="width:300px; height:300px; margin-left:15px; float: right;
  border: 1px solid #ddd;
  border-radius: 25px;
  padding: 5px;
  margin-right:20px;
  margin-left:20px;
  margin-bottom:40px;">
  <h3><b>Counselling Sessions</b></h3><br>
  <p style="font-size: 18px">

  We are offering personal counselling sessions to help you understand co-ordination between mental and physical health and 
  the importance of balanced diet with a proper diet chart.

  </p>
  </div>
</body>
</html>